package in.sipora.backend.modules.ai.web;

import in.sipora.backend.modules.ai.application.HydrationAdvisor;
import in.sipora.backend.modules.ai.web.AiDTOs.ChatRequest;
import in.sipora.backend.modules.ai.web.AiDTOs.ChatResponse;
import in.sipora.backend.modules.ai.web.AiDTOs.ClearSessionResponse;
import in.sipora.backend.modules.ai.web.AiDTOs.RecommendRequest;
import in.sipora.backend.modules.ai.web.AiDTOs.RecommendResponse;
import in.sipora.backend.shared.util.SecurityUtils;
import in.sipora.backend.shared.web.ApiResponse;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;

import jakarta.validation.Valid;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;

import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.servlet.mvc.method.annotation.SseEmitter;

import java.util.Optional;

/**
 * REST endpoints for the Aire AI hydration advisor.
 *
 * Three interaction modes:
 *
 *  POST /chat — Simple blocking request/response.
 *             Use for environments where SSE isn't supported.
 *
 *  POST /chat/stream — Server-Sent Events (SSE) streaming.
 *             The React frontend connects and receives tokens in real-time,
 *             creating a typewriter effect. Preferred mode for the web UI.
 *
 *  POST /recommend — Structured recommendation with product card output.
 *                 Takes preference, use case, and budget to generate
 *                 2-3 specific product suggestions with IDs.
 *
 *  DELETE /sessions/{sessionId} — Clears chat history for a session.
 *                       Call when the user starts a new conversation.
 *
 * Authentication:
 *  - Authenticated users get their userId as the default sessionId
 *    (persistent session across devices/tabs).
 *  - Guest users must supply their own sessionId in the request body
 *    (generated by frontend and stored in localStorage).
 */
@Slf4j
@RestController
@RequestMapping("/api/v1/ai")
@RequiredArgsConstructor
@Tag(name = "AI — Aire Advisor", description = "Gemini-powered hydration advisor and product recommender")
public class AiController {

    private static final long SSE_TIMEOUT_MS = 60_000L; // 60 seconds

    private final HydrationAdvisor hydrationAdvisor;

    // ── Blocking chat ==>

    @PostMapping("/chat")
    @Operation(
            summary = "Send a message to Aire and get a complete response",
            description = "Blocking endpoint — waits for the full response before returning. " +
                    "Use /chat/stream for a real-time typewriter experience."
    )
    public ResponseEntity<ApiResponse<ChatResponse>> chat(
            @Valid @RequestBody ChatRequest request) {

        ChatRequest enrichedRequest = enrichWithUserId(request);
        ChatResponse response = hydrationAdvisor.chat(enrichedRequest);
        return ResponseEntity.ok(ApiResponse.success("Response generated", response));
    }

    // ── Streaming chat ==>

    @PostMapping(value = "/chat/stream", produces = MediaType.TEXT_EVENT_STREAM_VALUE)
    @Operation(
            summary = "Stream Aire's response as Server-Sent Events",
            description = """
            Each SSE event is a JSON StreamEvent object:
            - type="token" → partial response chunk, append to display text
            - type="done" → stream finished, contains recommendedProductIds for product cards
            - type="error" → something went wrong

            Frontend usage:
              const es = new EventSource('/api/v1/ai/chat/stream', {method:'POST', ...});
              es.onmessage = e => {
                const ev = JSON.parse(e.data);
                if (ev.type === 'token') appendToChat(ev.content);
                if (ev.type === 'done')  showProductCards(ev.recommendedProductIds);
              };
            """
    )
    public SseEmitter streamChat(@Valid @RequestBody ChatRequest request) {
        SseEmitter emitter = new SseEmitter(SSE_TIMEOUT_MS);
        ChatRequest enrichedRequest = enrichWithUserId(request);

        // Timeout and error handlers
        emitter.onTimeout(() -> {
            log.debug("SSE timeout for session: {}", enrichedRequest.sessionId());
            emitter.complete();
        });
        emitter.onError(e -> log.debug("SSE error: {}", e.getMessage()));

        // Delegate to async service — runs on taskExecutor thread pool
        hydrationAdvisor.chatStream(enrichedRequest, emitter);
        return emitter;
    }

    // ── Recommendations ==>

    @PostMapping("/recommend")
    @Operation(
            summary = "Get product recommendations based on preferences",
            description = "Provide a preference description, optional use case and budget. " +
                    "Returns 2-3 recommended products with IDs for card rendering."
    )
    public ResponseEntity<ApiResponse<RecommendResponse>> recommend(
            @Valid @RequestBody RecommendRequest request) {

        RecommendRequest enrichedRequest = enrichRecommendWithUserId(request);
        RecommendResponse response = hydrationAdvisor.recommend(enrichedRequest);
        return ResponseEntity.ok(ApiResponse.success("Recommendations ready", response));
    }

    // ── Session management ==>

    @DeleteMapping("/sessions/{sessionId}")
    @Operation(
            summary = "Clear the chat history for a session",
            description = "Call when the user clicks 'New chat' to start fresh."
    )
    public ResponseEntity<ApiResponse<ClearSessionResponse>> clearSession(
            @PathVariable String sessionId) {

        hydrationAdvisor.clearSession(sessionId);
        return ResponseEntity.ok(ApiResponse.success(
                "Session cleared",
                new ClearSessionResponse(sessionId, "Chat history cleared")));
    }

    // ── Helpers ==>

    /**
     * For authenticated users: uses their UUID as the default sessionId.
     * This makes their conversation persistent across sessions / devices.
     * Guests must supply their own sessionId in the request.
     */
    private ChatRequest enrichWithUserId(ChatRequest request) {
        Optional<java.util.UUID> userId = SecurityUtils.getCurrentUserId();
        if (userId.isPresent() && (request.sessionId() == null || request.sessionId().isBlank())) {
            return new ChatRequest(request.message(), userId.get().toString());
        }
        return request;
    }

    private RecommendRequest enrichRecommendWithUserId(RecommendRequest request) {
        Optional<java.util.UUID> userId = SecurityUtils.getCurrentUserId();
        if (userId.isPresent() && (request.sessionId() == null || request.sessionId().isBlank())) {
            return new RecommendRequest(
                    request.preference(), request.useCase(),
                    request.maxBudget(), userId.get().toString());
        }
        return request;
    }
}